language: node_js
cache:
  directories:
    - ~/.npm
addons:
  apt:
    packages:
      - libsecret-1-dev
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test
        - npm run compile
      after_success: 
        - npm run codecov
    - stage: deploy
      if: branch = master
      script: npm run semantic-release

